plugins:
  - rubocop-minitest
  - rubocop-performance

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'vendor/**/*'

Style/Documentation:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Layout/LineLength:
  Max: 140

Metrics/ClassLength:
  Max: 200

Metrics/ModuleLength:
  Max: 200

Metrics/MethodLength:
  Max: 20
  Exclude:
    - 'lib/max/bot/multipart_upload.rb'

Metrics/AbcSize:
  Max: 30
  Exclude:
    - 'lib/max/bot/multipart_upload.rb'

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 10

Metrics/ParameterLists:
  Max: 9

Minitest/EmptyLineBeforeAssertionMethods:
  Enabled: false

Minitest/MultipleAssertions:
  Enabled: false

Gemspec/DevelopmentDependencies:
  EnforcedStyle: gemspec
